name: Backup Firestore

on:
  push:
    branches:
      - master
  schedule:
    - cron: '25 * * * *'

env:
  PROJECT_ID: money-tracker-app-89c86
  BUCKET: gs://backup-bucket-money-tracker
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      # Ensure the service account has roles/datastore.importExportAdmin and roles/storage.admin
      - name: Check IAM permissions
        run: |
          gcloud projects get-iam-policy $PROJECT_ID --flatten="bindings[].members" --format='table(bindings.role)' --filter="bindings.members:serviceAccount:${{ secrets.GCP_SA_KEY_EMAIL }}"
      - run: gcloud firestore export $BUCKET